// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7gC3wyJItM4Lr4a-jh21dGqTUc1jEomE',
    appId: '1:922554331011:web:3541e6c70a3eae8c9610b6',
    messagingSenderId: '922554331011',
    projectId: 'mfjh-2a6c3',
    authDomain: 'mfjh-2a6c3.firebaseapp.com',
    databaseURL: 'https://mfjh-2a6c3-default-rtdb.firebaseio.com',
    storageBucket: 'mfjh-2a6c3.firebasestorage.app',
    measurementId: 'G-DJ7P9HX9CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGvUYRF7p0WjHTQJpqKzLFBM0KdIL988',
    appId: '1:922554331011:android:c04be5e69bdef0f19610b6',
    messagingSenderId: '922554331011',
    projectId: 'mfjh-2a6c3',
    databaseURL: 'https://mfjh-2a6c3-default-rtdb.firebaseio.com',
    storageBucket: 'mfjh-2a6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApksfkWB3N77PgrviJR4P8zPLoESHKNHo',
    appId: '1:922554331011:ios:c06a7308419932339610b6',
    messagingSenderId: '922554331011',
    projectId: 'mfjh-2a6c3',
    databaseURL: 'https://mfjh-2a6c3-default-rtdb.firebaseio.com',
    storageBucket: 'mfjh-2a6c3.firebasestorage.app',
    iosBundleId: 'com.example.mysoreFashionJewelleryHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApksfkWB3N77PgrviJR4P8zPLoESHKNHo',
    appId: '1:922554331011:ios:c06a7308419932339610b6',
    messagingSenderId: '922554331011',
    projectId: 'mfjh-2a6c3',
    databaseURL: 'https://mfjh-2a6c3-default-rtdb.firebaseio.com',
    storageBucket: 'mfjh-2a6c3.firebasestorage.app',
    iosBundleId: 'com.example.mysoreFashionJewelleryHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7gC3wyJItM4Lr4a-jh21dGqTUc1jEomE',
    appId: '1:922554331011:web:6049ceeb4fbc7c629610b6',
    messagingSenderId: '922554331011',
    projectId: 'mfjh-2a6c3',
    authDomain: 'mfjh-2a6c3.firebaseapp.com',
    databaseURL: 'https://mfjh-2a6c3-default-rtdb.firebaseio.com',
    storageBucket: 'mfjh-2a6c3.firebasestorage.app',
    measurementId: 'G-YG9TSWTEG3',
  );

}